# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1227, 838)
        Form.setStyleSheet("/* Set style for app title widget */\n"
                "#titleWidget {\n"
                "    border-image: url(:/img/img/206954.jpg);\n"
                "    border-top-left-radius: 10px;\n"
                "    border-bottom-left-radius: 10px;\n"
                "}\n"
                "\n"
                "#titleWidget QLabel {\n"
                "    color: rgba(255, 255, 255, 0.8);\n"
                "    font-family: \"Stencil\";\n"
                "}\n"
                "\n"
                "#titleLabel1 {\n"
                "    font-size: 40px;\n"
                "}\n"
                "\n"
                "#titleLabel2 {\n"
                "    font-size: 30px;\n"
                "}\n"
                "\n"
                "/* Set style for function widget */\n"
                "#funcWidget {\n"
                "    background-color: #fff;\n"
                "    border-top-right-radius: 10px;\n"
                "    border-bottom-right-radius: 10px;\n"
                "    border-top: 2px solid #343434;\n"
                "    border-right: 2px solid #343434;\n"
                "    border-bottom: 2px solid #343434;\n"
                "}\n"
                "\n"
                "/* Set style for all the QLabel in function widget */\n"
                "#funcWidget QLabel {\n"
                "    color: #505050;\n"
                "}\n"
                "\n"
                "/* Set style for login label and register label in function widget */\n"
                "#loginLabel, #registerLabel_register_page {\n"
                "    font-family: \"Viner Hand ITC\";\n"
                "    font-size: 30px;\n"
                "}\n"
                "\n"
                "/* Set style for all the QLineEdit in function widget */\n"
                "#funcWidget QLineEdit {\n"
                "    border: 1px solid #e5ebf0;\n"
                "    border-radius: 5px;\n"
                "    padding: 5px 10px;\n"
                "    font-size: 15px;\n"
                "}\n"
                "\n"
                "#funcWidget QLineEdit:focus {\n"
                "    border-color: #5500ff;\n"
                "}\n"
                "\n"
                "/* Set style for all the buttons in function widget */\n"
                "#funcWidget QPushButton {\n"
                "    font-size: 12em;\n"
                "    border-radius: 5px;\n"
                "    color: #fff;\n"
                "}\n"
                "\n"
                "#funcWidget QPushButton:pressed {\n"
                "    padding-left: 10px;\n"
                "}\n"
                "\n"
                "/* Set style for login and create user button in function widget */\n"
                "#loginBtn_login_page, #registerBtn_register_page, #verify_otp_Btn_register_page {\n"
                "    background-color: #3554d1;\n"
                "}\n"
                "\n"
                "#loginBtn_login_page:hover, #loginBtn_login_page:pressed, #registerBtn_register_page:hover, #registerBtn_register_page:pressed, #verify_otp_Btn_register_page:hover, #verify_otp_Btn_register_page:pressed {\n"
                "    background-color: #0000ff;\n"
                "}\n"
                "\n"
                "\n"
                "/* Set style for exit button in function widget */\n"
                "#exitBtn_login_page {\n"
                "    background-color: #d10000;\n"
                "}\n"
                "\n"
                "#exitBtn_login_page:hover, #exitBtn_login_page:pressed {\n"
                "    background-color: #910000;\n"
                "}\n"
                "\n"
                "/* Set style for register and back button in function widget */\n"
                "#registerBtn_login_page, #backBtn_register_page ,#send_otp_Btn_register_page{\n"
                "    background-color: #55aa7f;\n"
                "}\n"
                "\n"
                "#registerBtn_login_page:hover, #registerBtn_login_page:pressed, #backBtn_register_page:hover, #backBtn_register_page:pressed,#send_otp_Btn_register_page:hover, #send_otp_Btn_register_page:pressed {\n"
                "    background-color: #3aad00;\n"
                "}\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "\n"
                "")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.titleWidget = QtWidgets.QWidget(Form)
        self.titleWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.titleWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.titleWidget.setObjectName("titleWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel1 = QtWidgets.QLabel(self.titleWidget)
        self.titleLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel1.setObjectName("titleLabel1")
        self.verticalLayout.addWidget(self.titleLabel1)
        self.titleLabel2 = QtWidgets.QLabel(self.titleWidget)
        self.titleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel2.setObjectName("titleLabel2")
        self.verticalLayout.addWidget(self.titleLabel2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.titleWidget, 0, 1, 2, 1)
        self.funcWidget = QtWidgets.QStackedWidget(Form)
        self.funcWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.funcWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.funcWidget.setObjectName("funcWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loginLabel = QtWidgets.QLabel(self.page)
        self.loginLabel.setStyleSheet("#loginLabel {\n"
                "    color: #000;\n"
                "}")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_5.addWidget(self.loginLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.email_label_login_page = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_label_login_page.setFont(font)
        self.email_label_login_page.setObjectName("email_label_login_page")
        self.verticalLayout_3.addWidget(self.email_label_login_page)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password_label_login_page = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label_login_page.setFont(font)
        self.password_label_login_page.setObjectName("password_label_login_page")
        self.verticalLayout_4.addWidget(self.password_label_login_page)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.exitBtn_login_page = QtWidgets.QPushButton(self.page)
        self.exitBtn_login_page.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/x-mark-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn_login_page.setIcon(icon)
        self.exitBtn_login_page.setObjectName("exitBtn_login_page")
        self.horizontalLayout.addWidget(self.exitBtn_login_page)
        self.registerBtn_login_page = QtWidgets.QPushButton(self.page)
        self.registerBtn_login_page.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/user-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerBtn_login_page.setIcon(icon1)
        self.registerBtn_login_page.setObjectName("registerBtn_login_page")
        self.horizontalLayout.addWidget(self.registerBtn_login_page)
        self.loginBtn_login_page = QtWidgets.QPushButton(self.page)
        self.loginBtn_login_page.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/login-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginBtn_login_page.setIcon(icon2)
        self.loginBtn_login_page.setObjectName("loginBtn_login_page")
        self.horizontalLayout.addWidget(self.loginBtn_login_page)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 1, 1, 1)
        self.funcWidget.addWidget(self.page)
        
        #registation page
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.registerLabel_register_page = QtWidgets.QLabel(self.page_2)
        self.registerLabel_register_page.setStyleSheet("#registerLabel_register_page {\n"
        "    color: #000;\n"
        "}")
        self.registerLabel_register_page.setAlignment(QtCore.Qt.AlignCenter)
        self.registerLabel_register_page.setObjectName("registerLabel_register_page")
        self.verticalLayout_6.addWidget(self.registerLabel_register_page)
        
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gmail_label_register_page = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gmail_label_register_page.setFont(font)
        self.gmail_label_register_page.setObjectName("gmail_label_register_page")
        self.verticalLayout_7.addWidget(self.gmail_label_register_page)
        self.gmail_lineEdit_register_page = QtWidgets.QLineEdit(self.page_2)
        self.gmail_lineEdit_register_page.setMinimumSize(QtCore.QSize(300, 0))
        self.gmail_lineEdit_register_page.setClearButtonEnabled(True)
        self.gmail_lineEdit_register_page.setObjectName("gmail_lineEdit_register_page")
        self.verticalLayout_7.addWidget(self.gmail_lineEdit_register_page)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        
        self.verticalLayout_name = QtWidgets.QVBoxLayout()
        self.verticalLayout_name.setSpacing(10)
        self.verticalLayout_name.setObjectName("verticalLayout_name")
        self.name_label_register_page = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label_register_page.setFont(font)
        self.name_label_register_page.setObjectName("name_label_register_page")
        self.verticalLayout_name.addWidget(self.name_label_register_page)
        self.name_lineEdit_register_page = QtWidgets.QLineEdit(self.page_2)
        self.name_lineEdit_register_page.setMinimumSize(QtCore.QSize(300, 0))
        self.name_lineEdit_register_page.setClearButtonEnabled(True)
        self.name_lineEdit_register_page.setObjectName("name_lineEdit_register_page")
        self.verticalLayout_name.addWidget(self.name_lineEdit_register_page)
        self.verticalLayout_6.addLayout(self.verticalLayout_name)

        self.verticalLayout_otp = QtWidgets.QVBoxLayout()
        self.verticalLayout_otp.setSpacing(10)
        self.verticalLayout_otp.setObjectName("verticalLayout_otp")
        self.otp_label_register_page = QtWidgets.QLabel(self.page_2)
        font_otp = QtGui.QFont()
        font_otp.setPointSize(10)
        self.otp_label_register_page.setFont(font_otp)
        self.otp_label_register_page.setObjectName("otp_label_register_page")
        self.verticalLayout_otp.addWidget(self.otp_label_register_page)
        self.otp_lineEdit_register_page = QtWidgets.QLineEdit(self.page_2)
        self.otp_lineEdit_register_page.setMinimumSize(QtCore.QSize(300, 0))
        self.otp_lineEdit_register_page.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.otp_lineEdit_register_page.setClearButtonEnabled(True)
        self.otp_lineEdit_register_page.setObjectName("otp_lineEdit_register_page")
        self.verticalLayout_otp.addWidget(self.otp_lineEdit_register_page)
        reg_ex = QRegExp("[0-9]{6}")
        self.otp_lineEdit_register_page.setValidator(QRegExpValidator(reg_ex))
        self.verticalLayout_6.addLayout(self.verticalLayout_otp)

        self.horizontalLayout_2_otp = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2_otp.setSpacing(5)
        self.horizontalLayout_2_otp.setObjectName("horizontalLayout_2_otp")
        self.send_otp_Btn_register_page = QtWidgets.QPushButton(self.page_2)
        self.send_otp_Btn_register_page.setMinimumSize(QtCore.QSize(0, 30))
        icon3_otp = QtGui.QIcon()
        icon3_otp.addPixmap(QtGui.QPixmap(":/icon/icon/redo-5-128.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_otp_Btn_register_page.setIcon(icon3_otp)
        self.send_otp_Btn_register_page.setObjectName("send_otp_Btn_register_page")
        self.horizontalLayout_2_otp.addWidget(self.send_otp_Btn_register_page)
        self.verify_otp_Btn_register_page = QtWidgets.QPushButton(self.page_2)
        self.verify_otp_Btn_register_page.setMinimumSize(QtCore.QSize(0, 30))
        icon4_otp = QtGui.QIcon()
        icon4_otp.addPixmap(QtGui.QPixmap(":/icon/icon/check-mark-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verify_otp_Btn_register_page.setIcon(icon4_otp)
        self.verify_otp_Btn_register_page.setObjectName("verify_otp_Btn_register_page")
        self.horizontalLayout_2_otp.addWidget(self.verify_otp_Btn_register_page)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2_otp)
        
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.password_label_register_page = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label_register_page.setFont(font)
        self.password_label_register_page.setObjectName("password_label_register_page")
        self.verticalLayout_8.addWidget(self.password_label_register_page)
        self.password_lineEdit_register_page = QtWidgets.QLineEdit(self.page_2)
        self.password_lineEdit_register_page.setMinimumSize(QtCore.QSize(300, 0))
        self.password_lineEdit_register_page.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit_register_page.setClearButtonEnabled(True)
        self.password_lineEdit_register_page.setObjectName("password_lineEdit_register_page")
        self.verticalLayout_8.addWidget(self.password_lineEdit_register_page)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backBtn_register_page = QtWidgets.QPushButton(self.page_2)
        self.backBtn_register_page.setMinimumSize(QtCore.QSize(0, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-80-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn_register_page.setIcon(icon3)
        self.backBtn_register_page.setObjectName("backBtn_register_page")
        self.horizontalLayout_2.addWidget(self.backBtn_register_page)
        self.registerBtn_register_page = QtWidgets.QPushButton(self.page_2)
        self.registerBtn_register_page.setMinimumSize(QtCore.QSize(0, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/check-mark-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerBtn_register_page.setIcon(icon4)
        self.registerBtn_register_page.setObjectName("registerBtn_register_page")
        self.horizontalLayout_2.addWidget(self.registerBtn_register_page)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 2, 1, 1, 1)
        self.funcWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.funcWidget, 0, 2, 2, 1)
        spacerItem10 = QtWidgets.QSpacerItem(111, 835, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 0, 2, 1)
        spacerItem11 = QtWidgets.QSpacerItem(110, 835, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 3, 2, 1)

        self.retranslateUi(Form)
        self.funcWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel1.setText(_translate("Form", "MEET U"))
        self.titleLabel2.setText(_translate("Form", "Hand Sign Recognition Model"))
        self.loginLabel.setText(_translate("Form", "Login"))
        self.email_label_login_page.setText(_translate("Form", "Email"))
        self.password_label_login_page.setText(_translate("Form", "Password"))
        self.exitBtn_login_page.setText(_translate("Form", "Exit"))
        self.registerBtn_login_page.setText(_translate("Form", "Register"))
        self.loginBtn_login_page.setText(_translate("Form", "Login"))

        self.registerLabel_register_page.setText(_translate("Form", "Register"))
        self.gmail_label_register_page.setText(_translate("Form", "Email"))
        self.name_label_register_page.setText(_translate("Form", "Name"))
        self.otp_label_register_page.setText(_translate("Form", "OTP"))
        self.send_otp_Btn_register_page.setText(_translate("Form", "Send OTP"))
        self.verify_otp_Btn_register_page.setText(_translate("Form", "Verify"))
        self.password_label_register_page.setText(_translate("Form", "Password"))
        self.backBtn_register_page.setText(_translate("Form", "Back"))
        self.registerBtn_register_page.setText(_translate("Form", "Create"))
from static import resource_rc
